### ISSUE TITLE
Difference in return type of `readEntry()`

### ISSUE THREAD

**Issue by thalesog** [overlookmotel/yauzl-promise#32]
Hello @overlookmotel, in first place, thanks for the rewrite of `yauzl`, that lib was needing a updated fork.

Using the `readEntry()` method, i noticed a slight diference between the types and the actual return of the method.

Example:

Look at `fileName | filename` and `filenameLength | fileNameLength`

![Screenshot 2023-07-29 at 21 26 51](https://github.com/overlookmotel/yauzl-promise/assets/4792793/fdf81329-311a-49d9-87c0-2dffe03c7aab)
![Screenshot 2023-07-29 at 21 27 03](https://github.com/overlookmotel/yauzl-promise/assets/4792793/7bd98faf-362c-4d56-8901-a71db11bb980)

**Comment by overlookmotel** [comment]
Sorry for the slow response. I missed this somehow.

This library does not provide types. I assume the types you're using must be from DefinitelyTyped (or somewhere else?). I'd suggest submitting a PR there.

Closing this issue, not because your issue is invalid, but because the types are not under my control.

I don't use TypeScript myself, and am not at all familiar with it, so would not be capable of maintaining the types. Therefore I don't feel it'd be a good idea to provide types as part of the library.
