### ISSUE TITLE
[Possible Bug] Unzipping on MacOS fails inconsistently

### ISSUE THREAD

**Issue by ayushmanchhabra** [overlookmotel/yauzl-promise#38]
This package is used by `nw-builder` to unzip some NW.js binaries. It fails inconsistently when trying to unzip the file on MacOS. Here are some GitHub Actions logs to demonstrate this behaviour:
- https://github.com/nwutils/nw-builder/actions/runs/7657926180
- https://github.com/nwutils/nw-builder/actions/runs/7659432785

Note that in the first link, 1/4 unzip operations fail but after simply rebasing the pull request, 4/4 fail.

https://github.com/nwutils/nw-builder/blob/9af082c33acf4a356bc8efa5f005d268d817efe3/src/util.js#L481
Here is how we use the package.

Please let me know if you require any more information.

p.s.: thanks for creating this awesome package

**Comment by overlookmotel** [comment]
Hi. Thanks for reporting.

It's quite hard to diagnose from this info. Are you able to run CI in "debug mode" or something to get a stack trace? I'm not familiar with Vitest, so not sure how to do this, but assume it should be possible.

**Comment by ayushmanchhabra** [comment]
https://github.com/nwutils/nw-builder/actions/runs/7659747681
I re-ran the actions in debug mode but don't think they would help much...

I will try to come up with a minimal repro!

**Comment by overlookmotel** [comment]
Thanks. What is weird is that 3 of the runs fail with one error, and the 4th with a different one.

1 x `EISDIR: illegal operation on a directory, read`
3 x `End of Central Directory Record not found`

"End of Central Directory Record not found" indicates that it thinks the ZIP is not well-formed. Usually the problem is it's not been written in full and is missing the EOCD (which at very end of a ZIP file).

The `EISDIR` error is much more mysterious. I believe that's the error you get when you try to open a file but the path given isn't a file - it's a directory. That makes little sense to have its ultimate cause in `yauzl-promise`, as the only thing it does with a file is try to open the path you give it.

I wonder if you have a problem with the code which is calling `yauzl-promise`. Like, for example, there's a timing problem and whatever is downloading/writing the ZIP which you're trying to unzip hasn't completed yet before `yauzl-promise` tries to open it. Maybe that bug is only apparent on MacOS not because it's MacOS specifically but just that the timing of the code is slightly different on different OSs?

I'm not saying I'm not open to possibility that `yauzl-promise` is to blame, but could you please investigate further your end, and rule out other possibilities please?

**Comment by ayushmanchhabra** [comment]
> for example, there's a timing problem and whatever is downloading/writing the ZIP which you're trying to unzip hasn't completed yet before yauzl-promise tries to open it.

Yes, I can see this being a possible cause! I will try to debug and get back to you.

**Comment by ayushmanchhabra** [comment]
Looks like the issue is with how files are being downloaded. If I `wget` or `curl` and use `yauzl-promise`, I don't get any errors.
