### ISSUE TITLE
Is the usage of streams problematic?

### ISSUE THREAD

**Issue by adhanji8** [overlookmotel/yauzl-promise#41]
Sorry for creating an issue out of this, you can close it right after. I just wanted clarification regarding the usage of streams in this library. 

Yauzl has a point regarding streams that said: 
Follow the spec. Don't scan for local file headers. Read the central directory for file metadata. (see [No Streaming Unzip API](https://www.npmjs.com/package/yauzl#no-streaming-unzip-api)).

I noticed that this library uses Streams. Is this an implementation detail that differs from the original Yauzl, or are streams being used in a different way that doesn't break the spec? Apologies for the potentially stupid question, appreciate it!

**Comment by overlookmotel** [comment]
Hi. Interesting question.

This library does not accept the input ZIP file as a stream. It requires random access, for the reasons you've quoted.

It starts at the end of the ZIP file and works backwards to find the Central Directory.

But once the Central Directory is found, that directory identifies the start and end positions of each file in the ZIP. At that point, `yauzl-promise` switches to streams in order to read each individual file from the ZIP and stream it out to the user.

This is exactly how `yauzl` works too, and in no way violates the ZIP spec.

I hope that makes sense. If it does, please close the issue. But if it doesn't, feel free to ask more questions!

**Comment by adhanji8** [comment]
Thank you for the amazing explanation and also for maintaining is incredible project. You are sincerely appreciated 🙏. Thank you.
